[package]
name = "server"
version = "0.2.24"
edition = "2021"
build = "src/build.rs"

[features]
default = []
jemalloc = ["dep:tikv-jemallocator"]
tokio-console = ["dep:console-subscriber", "tokio/tracing"]

[dependencies]
anyhow = "1.0.86"
async-stream = "0.3.5"
async-trait = "0.1.80"
atone = "0.3.7"
axum = "0.7.5"
axum-server = { version = "0.6.0", features = ["tls-rustls"] }
bcrypt = "0.15.1"
blake3 = "1.5.1"
bytes = "1.6.0"
clap = { version = "4.5.4", features = ["derive"] }
console-subscriber = { version = "0.2.0", optional = true }
dashmap = "5.5.3"
figlet-rs = "0.1.5"
figment = { version = "0.10.18", features = ["json", "toml", "env"] }
flume = "0.11.0"
futures = "0.3.30"
iggy = { path = "../sdk" }
jsonwebtoken = "9.3.0"
keepcalm = "0.3.5"
moka = { version = "0.12.5", features = ["future"] }
prometheus-client = "0.22.2"
quinn = { version = "0.11.1" }
rcgen = "0.13.1"
ring = "0.17.8"
rmp-serde = "1.3.0"
rustls = { version = "0.23.10" }
rustls-pemfile = "2.1.2"
serde = { version = "1.0.203", features = ["derive", "rc"] }
serde_json = "1.0.117"
serde_with = { version = "3.8.1", features = ["base64", "macros"] }
sled = "0.34.7"
static-toml = "1.2.0"
strip-ansi-escapes = "0.2.0"
sysinfo = "0.30.12"
thiserror = "1.0.61"
tokio = { version = "1.38.0", features = ["full"] }
tokio-native-tls = "0.3.1"
toml = "0.8.14"
tower-http = { version = "0.5.2", features = [
    "add-extension",
    "cors",
    "trace",
] }
tracing = { version = "0.1.40" }
tracing-appender = "0.2.3"
tracing-subscriber = { version = "0.3.18", features = ["fmt"] }
ulid = "1.1.2"
uuid = { version = "1.8.0", features = ["v4", "fast-rng", "zerocopy"] }
xxhash-rust = { version = "0.8.10", features = ["xxh32"] }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = { version = "0.5", optional = true }

[build-dependencies]
figment = { version = "0.10.18", features = ["json", "toml", "env"] }
serde_json = "1.0.117"
vergen = { version = "8.3.1", features = [
    "build",
    "cargo",
    "git",
    "gitcl",
    "rustc",
] }

[[bin]]
name = "iggy-server"
path = "src/main.rs"

# This is a workaround for cargo-udeps to ignore these dependencies
# in case if feature 'tokio-console' is enabled.
[package.metadata.cargo-udeps.ignore]
normal = ["tracing-appender", "strip-ansi-escapes"]
